feat: allow disabling some timeouts and add error types
nytamin/threadedClass pull request #72
Opened 2022-11-07 11:33 UTC by ianshade

Allows disabling some timeouts by setting their respective options to `0`.
Adds new error types for some timeouts, to allow appropriate handling by the users.
No longer cleans up the instance in case of an error or timeout when restarting, allowing for a manual restart afterwards.
Adds previously undocumented options to README.md.

2022-11-07 11:41 UTC, Julusian commented
I'm curious as to why/when you would want to disable some of these timeouts. 
At the very least if you disable the timeouts, then when the timeouts used to fire you would end up with promises which never resolve

2022-11-07 12:36 UTC, ianshade commented
@Julusian why would these promises never resolve in the first place? Are we not trusting threadedclass to do things correctly, or are we not trusting _our code_ that we're running via threadedclass?

2022-11-08 21:16 UTC, jstarpl commented
> @Julusian why would these promises never resolve in the first place? Are we not trusting threadedclass to do things correctly, or are we not trusting _our code_ that we're running via threadedclass?

I suppose we don't trust the code running via threadedclass? It's a black box and as such should generally not be trusted. In most cases it's _our_ in a very limited sense, having some sort of a timeout guard (even if very large) feels like a good idea?

2022-11-09 08:12 UTC, nytamin requested changes
>Allows disabling some timeouts by setting their respective options to 0.

I think that it would be a bad idea to disable the timeouts, they are there to protect against "badly written" user-code running in the threads, like if it locks up the main event-loop, not resolving promises etc..
However if you really really want to anyway I'm not against including the option to do so.


>Adds new error types for some timeouts, to allow appropriate handling by the users.

The new error types are a welcome addition!

>No longer cleans up the instance in case of an error or timeout when restarting, allowing for a manual restart afterwards.

I don't this is the way to go as this will cause memory leaks.
When there is a problem during auto-restart an `error` event is emitted, allowing the user-code to decide what to do.
The user-code might decide to _not_ manually restart the existing instance, but rather fire up another instance, resulting in the memory-leak.

An alternate solution might be to add another option to "retryAutoRestart" which when enabled won't emit the error but rather retry to restart it (and also not clean up the instance). That should be a separate PR though.

2022-11-09 09:29 UTC, ianshade commented
@jstarpl and @nytamin, I see where you're coming from, but it's just an extra feature. A nice-to-have. If you ran that same user-code in a single-threaded event loop environment, would there be any of that protection available? I think it is reasonable to give an option to disable it, instead of forcing the users to use trial and error to establish the right values, or to set extremely large values if they completely don't know how long their code might execute (or if they believe there is an external factor contributing to things getting _slow_ and timing out).

> The user-code might decide to not manually restart the existing instance, but rather fire up another instance, resulting in the memory-leak.

Does the user want to auto restart again, or do they want to do something else (forget about that instance, make a new one with different constructor arguments, increase the timeouts, etc.)? We don't know, but the way we're using threadedclass in Sofie Core, it feels like doing it the way proposed in this PR is going to make it relatively easy to fix the issues we're having at TV 2, making the least amount of changes in threadedclass. We could probably use the WeakRef / FinalizationCallback to tell if the user code no longer references the wrapped instance after this happens, but there is a simpler solution:

> add another option to "retryAutoRestart" which when enabled won't emit the error but rather retry to restart

One might still need some sort of feedback and ability to make some decisions. What if we wanted to act different if restart fails _n_ times in a row? How about adding an option to `disableCleanUpAfterFailedRestart` (`false` by default), or `cleanUpAfterFailedRestart` (`true` by default)?

2022-11-18 11:45 UTC, ianshade commented
I updated the PR deacription with current changes.

2022-11-23 11:27 UTC, merged